#!/usr/bin/env python3
"""Export a deterministic OpenSCAD villa model in millimetres."""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from common import bbox, floor_bounds, load_json, rooms_by_floor

MM=1000.0

def f(v:float)->str: return f"{v*MM:.3f}".rstrip("0").rstrip(".")

def opening_matches_wall(opening:dict[str,Any],wall:dict[str,Any])->bool:
    if opening["floor_id"]!=wall["floor_id"] or opening["wall"]["orientation"]!=wall["orientation"]: return False
    if abs(float(opening["wall"]["coordinate_m"])-float(wall["start_m"][0 if wall["orientation"]=="vertical" else 1]))>0.01: return False
    pos=float(opening["position_m"]); half=float(opening["width_m"])/2
    start=float(wall["start_m"][1 if wall["orientation"]=="vertical" else 0]); end=float(wall["end_m"][1 if wall["orientation"]=="vertical" else 0])
    lo,hi=sorted((start,end)); return pos+half>=lo and pos-half<=hi


def wall_scad(wall:dict[str,Any],openings:list[dict[str,Any]],z:float)->str:
    x1,y1=wall["start_m"]; x2,y2=wall["end_m"]; t=wall["thickness_m"]; h=wall["height_m"]
    if wall["orientation"]=="horizontal":
        x=min(x1,x2); y=y1-t/2; length=abs(x2-x1); base=f"translate([{f(x)},{f(y)},{f(z)}]) cube([{f(length)},{f(t)},{f(h)}]);"
    else:
        x=x1-t/2; y=min(y1,y2); length=abs(y2-y1); base=f"translate([{f(x)},{f(y)},{f(z)}]) cube([{f(t)},{f(length)},{f(h)}]);"
    cuts=[]
    for op in openings:
        if not opening_matches_wall(op,wall): continue
        pos=op["position_m"]; width=op["width_m"]+0.04
        sill=0 if "swing" in op else op.get("sill_height_m",0.9); height=op.get("height_m",2.2)+0.04
        if wall["orientation"]=="horizontal": cuts.append(f"translate([{f(pos-width/2)},{f(y1-t)},{f(z+sill)}]) cube([{f(width)},{f(t*2)},{f(height)}]);")
        else: cuts.append(f"translate([{f(x1-t)},{f(pos-width/2)},{f(z+sill)}]) cube([{f(t*2)},{f(width)},{f(height)}]);")
    if not cuts: return base
    return "difference(){\n  "+base+"\n  "+"\n  ".join(cuts)+"\n}"


def generate_scad(plan:dict[str,Any])->str:
    lines=["// Generated by villa-floorplan-cad. Units: millimetres.","$fn=48;",""]
    openings=plan.get("openings",[]); slab_t=0.20
    lines.append("module villa_model(){")
    for floor in sorted(plan["floors"],key=lambda x:x["level_m"]):
        fx,fy,fw,fd=floor_bounds(plan,floor["id"]); z=floor["level_m"]
        lines.append(f"  // {floor['name']} slab")
        lines.append(f"  color([0.72,0.72,0.72]) translate([{f(fx)},{f(fy)},{f(z-slab_t)}]) cube([{f(fw)},{f(fd)},{f(slab_t)}]);")
        lines.append(f"  // {floor['name']} walls with door/window openings")
        for wall in plan["walls"]:
            if wall["floor_id"]==floor["id"]:
                lines.append("  "+wall_scad(wall,openings,z).replace("\n","\n  "))
        for door in plan.get("doors",[]):
            if door["floor_id"]!=floor["id"]: continue
            hx,hy=door["hinge_m"]; w=door["width_m"]
            if door["wall"]["orientation"]=="horizontal": lines.append(f"  color([0.45,0.25,0.10]) translate([{f(hx)},{f(hy-0.025)},{f(z)}]) cube([{f(w)},{f(0.05)},{f(door['height_m'])}]);")
            else: lines.append(f"  color([0.45,0.25,0.10]) translate([{f(hx-0.025)},{f(hy)},{f(z)}]) cube([{f(0.05)},{f(w)},{f(door['height_m'])}]);")
        for win in plan.get("windows",[]):
            if win["floor_id"]!=floor["id"]: continue
            c,p,w=win["wall"]["coordinate_m"],win["position_m"],win["width_m"]
            if win["wall"]["orientation"]=="horizontal": lines.append(f"  color([0.2,0.65,0.9,0.45]) translate([{f(p-w/2)},{f(c-0.015)},{f(z+win['sill_height_m'])}]) cube([{f(w)},{f(0.03)},{f(win['height_m'])}]);")
            else: lines.append(f"  color([0.2,0.65,0.9,0.45]) translate([{f(c-0.015)},{f(p-w/2)},{f(z+win['sill_height_m'])}]) cube([{f(0.03)},{f(w)},{f(win['height_m'])}]);")
        for room in rooms_by_floor(plan,floor["id"]):
            if room["type"]!="stair": continue
            x,y,w,d=bbox(room); steps=20; tread=d/steps; rise=floor["floor_to_floor_height_m"]/steps
            lines.append(f"  // stair {room['id']}")
            for i in range(steps): lines.append(f"  color([0.65,0.65,0.65]) translate([{f(x+0.1)},{f(y+i*tread)},{f(z+i*rise)}]) cube([{f(max(0.1,w-0.2))},{f(tread+0.01)},{f(rise)}]);")
        for room in rooms_by_floor(plan,floor["id"]):
            if room["type"]=="elevator":
                x,y,w,d=bbox(room); lines.append(f"  // elevator shaft volume {room['id']}"); lines.append(f"  color([0.35,0.35,0.38,0.25]) translate([{f(x)},{f(y)},{f(z)}]) cube([{f(w)},{f(d)},{f(floor['clear_height_m'])}]);")
    top=max(plan["floors"],key=lambda x:x["level_m"]); fx,fy,fw,fd=floor_bounds(plan,top["id"]); roof_z=top["level_m"]+top["floor_to_floor_height_m"]; parapet=plan.get("standards",{}).get("parapet_height_m",1.1); t=plan.get("standards",{}).get("external_wall_thickness_m",0.25)
    lines.append(f"  color([0.72,0.72,0.72]) translate([{f(fx)},{f(fy)},{f(roof_z-slab_t)}]) cube([{f(fw)},{f(fd)},{f(slab_t)}]);")
    lines.extend([
        f"  translate([{f(fx)},{f(fy)},{f(roof_z)}]) cube([{f(fw)},{f(t)},{f(parapet)}]);",
        f"  translate([{f(fx)},{f(fy+fd-t)},{f(roof_z)}]) cube([{f(fw)},{f(t)},{f(parapet)}]);",
        f"  translate([{f(fx)},{f(fy)},{f(roof_z)}]) cube([{f(t)},{f(fd)},{f(parapet)}]);",
        f"  translate([{f(fx+fw-t)},{f(fy)},{f(roof_z)}]) cube([{f(t)},{f(fd)},{f(parapet)}]);",
    ])
    lines.append("}"); lines.append("villa_model();"); return "\n".join(lines)+"\n"


def main():
    p=argparse.ArgumentParser(description=__doc__); p.add_argument("plan"); p.add_argument("--output",default=None)
    a=p.parse_args(); path=Path(a.plan).expanduser().resolve(); out=Path(a.output).expanduser().resolve() if a.output else path.parent/"villa-model.scad"; out.parent.mkdir(parents=True,exist_ok=True); out.write_text(generate_scad(load_json(path)),encoding="utf-8"); print(out)
if __name__=="__main__": main()
